export const GET_USERS = 'GET_USERS'
export const SET_USERS ="SET_USERS"
export const GET_AUTHED_USER = 'GET_AUTHED_USER'
export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const UPDATE_USER_QUESTION = 'UPDATE_USER_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const GET_QUESTIONS = 'GET_QUESTIONS'
export const SET_QUESTIONS='SET_QUESTIONS'
export const SET_NEW_QUESTION='SET_NEW_QUESTION'
export const API='API'
export const API_START='API_START'
export const API_END='API_END'
export const APP_INIT='APP_INIT'
export const UPDATE_QUESTION_ANSWER='UPDATE_QUESTION_ANSWER'
export const UPDATE_USER_ANSWER='UPDATE_USER_ANSWER'
export const UPDATE_ANSWER='UPDATE_ANSWER'






